### ISSUE TITLE
Need A Readme For Tools!

### ISSUE THREAD

**Issue by Xeek3y** [BBerastegui/dockers#1]
Hey thanks for the tools tho <3
i'm facing a problem currently and i wanna ask....
I pulled aquatone in docker on my windows machine and from the aquatone usage i'm running something like:  
**type .\subdomain.txt | docker run -it bberastegui/aquatone:latest**

but it doesn't seems to work :/
need a little guidance to run this, i'm not sure what i did wrong but yeah i'm doing definetly wrong because i'm a first time user :p

**Comment by BBerastegui** [comment]
Hey! What you are experiencing here is not a problem with the tool but on how you use docker.

More info: https://riptutorial.com/docker/example/10313/passing-stdin-to-the-container

Cheers!

Edit: Glad to hear that the dockerization of the tools was helpful btw <3
